### ISSUE TITLE
Uncaught SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by HashBan** [apankowski/doc88-downloader#3]
When I enter the page numbers I end up with this error.
![image](https://user-images.githubusercontent.com/120596670/207687427-05d3d198-6c35-43dd-bd07-dc197a7216d2.png)

**Comment by apankowski** [comment]
@HashBan you get this error because you're modifying function definition in a way making it invalid.

To avoid the error, as per [instructions in README](https://github.com/apankowski/doc88-downloader#instructions):

1. execute step 6 or 7 exactly as it is described -- don't change the function code from the file like you did in the image
2. then execute step 8 from the README: type `downloadPages(1, 2)` (if you want to download pages 1--2) and confirm with <kbd>Enter</kbd>

**Comment by apankowski** [comment]
closing the issue due to lack of activity (and because it's not really an issue with the script, but a problem with using it)
